export const SUBMIT_ANSWER = "SUBMIT_ANSWER";
export const GET_PREVIOUS_QUESTION = "PREV_QUESTION";
export const GET_NEXT_QUESTION = "GET_NEXT_QUESTION";
export const ADD_COMPLETED_QUESTION = "ADD_COMPLETED_QUESTION";
export const TOGGLE_QUIZ_STATUS = "TOGGLE_QUIZ_STATUS";
